### ISSUE TITLE
bindNewEnvironment function

### ISSUE THREAD

**Issue by Lanayx** [JohSand/Orsak#1]
Hi! Thank you for this amazing library, it really sums up current F# best practices. What I'm currently missing is an ability to transform effects from one environment to another. For example let's say we have 2 interfaces
```fsharp
type IPriceProvider =
    abstract member GetPrice : string -> Task<decimal>
type IPriceProviders =
    abstract member PriceProviders: IPriceProvider[]
    
let getPrice code =
    Effect.Create(fun (priceProvider : #IPriceProvider) ->
        priceProvider.GetPrice code
    )
let getPriceProviders() =
    Effect.Create(fun (priceProviders : #IPriceProviders) ->
        priceProviders.PriceProviders
    )    
```
In the root I only initialize `IPriceProviders` interface, while somewhere in the middle I'll need to remap effect type to another environment. 
![image](https://user-images.githubusercontent.com/3329606/230973166-57204f27-7eea-43cc-a8bd-553afcc275ed.png)

**Comment by JohSand** [comment]
Hi,

I'm not sure I understand. The normal case when adding additional effects is that the constraints propagate, e.g. 
`('env when ('env :> IPriceProvider and 'env :> IPriceProviders)` 

For the example in question, is it needed to lift IPriceProvider.GetPrice into an effect?

To me it looks like it should be possible to just call GetPrice on the IPriceProviders directly, and bind the tasks.

Or possibly, somethings like
```fsharp
let getPrice code :Effect<#IPriceProviders, decimal array, _> ) =
    Effect.Create(fun (priceProvider : #IPriceProviders) ->
        Task.WhenAll(priceProviders.PriceProviders |> Array.map (fun p -> p.GetPrice code) )
    )
```

**Comment by Lanayx** [comment]
This is just an example of a problem where root env doesn't describe all possible dependencies used all over application. We have a pretty big backend app and we use environment remapping quite often. Sometimes it is impossible to fully construct all dependencies in the root, sometimes it's not done in the root due to some performance considerations, but rather load additional dependencies in runtime based on some conditions.
In your suggestion you propose to put domain logic inside effect which is not desirable.

**Comment by JohSand** [comment]
Well, the pattern of separating the effect and the effectProvider is to allow deferring the creation of the effect, and it is also often fruitful create the env in a scoped fashion.

But switching env in the middle does not seem to make sense to me. If you have an implementation in mind I can take a look.

**Comment by Lanayx** [comment]
Real world case is the following. We have business logic that can be executed by several different providers, while the provider is selected dynamically in runtime. So, first we need one env that allow us to go to database and find the provider, then another env that constructs main env using the information. With the main env we run the following business logic (can be hundreds of lines):
```fsharp
let doSmth env params =
   task {
       if params.flag then
           do! f1 env
       else 
           do! f2 env
    }
```
f1 and f2 a generic business flows implemented by both providers, they are defined in the following way
```fsharp
let f1 env =
    match env.Provider with
    | "Provider1" -> Provider1.f1 env
    | "Provider2" -> Provider2.f1 env
```
Each provider f1 implementation is complex and has some provider-specific functions, for example
```fsharp
module Provider1 =
    type IF1Env =
        inherit IAuthData
        inherit ISpecificFunction1
        inherit ISpecificFunction2
    let f1 env =
        let newEnv = {
            new IF1Env with 
                member _.Auth = env.Auth
                member _.SpecificFunction1 = Profider1Client.SpecificFunction1 env
                member _.SpecificFunction2 = Profider1Client.SpecificFunction2 env
         }
         doF1ProviderLogic newEnv
```
and finally goes provider-specific logic

```fsharp
let doF1ProviderLogic env =
    task {
        do! specificFunction1 env
        do! specificFunction2 env
    }
```

So, it's not practical to raise low-level interfaces `ISpecificFunction1` and `ISpecificFunction2` to the root level, since they are relevant to only one provider type and don't make sense for other providers. Such low-level interfaces should only be visible in the Provider1-related assembly and not to pollute global scope.

**Comment by JohSand** [comment]
I still don't think I understand how you want bindNewEnvironment to work.

The current design of Orsak encourages all effect-implementations and provider-implementations to be defined at the bottom (so close to the Program.fs-file), with files higher up en the project unaware of this. The typical case would be to maybe create an environment and have one effect per request, and run that in the routing layer in a Giraffe app, for example. 

If you somehow were to change the type of the effect midway, from 'env1 to 'env2 say, you would still need to create an 'env2 at the route layer to run the effect.

That being said, nothing prevents you from running an effect whenever you want. And you can bind the result of an executed effect inside another effect, since the result of an effect is just a ValueTask<Result<'T, 'Err>>.

**Comment by Lanayx** [comment]
Thank you for the hint! With that I was able to write that function myself and fix my initial `getBestPrice` function in the following way:
![image](https://user-images.githubusercontent.com/3329606/231901844-da9632d9-7e20-42bd-91a3-4eecfdc1bc81.png)
Do you think this function can be added to the library?

**Comment by JohSand** [comment]
Sure, but I need to think of a more descriptive name.
