### ISSUE TITLE
Use ply instead of custom value task builder

### ISSUE THREAD

**Issue by Lanayx** [JohSand/Orsak#4]
I think it will make more sense to take dependency on ply rather than having local value task builder
https://github.com/crowded/ply

**Comment by JohSand** [comment]
Hi,

Any special reason you would prefer Ply? I would prefer to take as few dependencies as possible, and my hope is that F# will soon get a native ValueTaskBuilder, and then I would use that.

**Comment by Lanayx** [comment]
I think it's because of responsibility delegation and confidence. Ply specializes on task and valuetask builders and has been used in many projects, so it should be stable enough to rely on. If there is some issue found with vtask builder regardless in this project or another - the fix in common library will benefit everyone. Also there will be no need to carry the burden of valuetask builder support in future (say when .net or F# introduce breaking changes).
So for me it makes a lot of sense to take that dependency unless it appears to be impossible due to some objective reasons.

**Comment by JohSand** [comment]
I have considered it, but since there are some extra extensions I want on the valuetask builder anyways, I think I will keep using my own until it lands in fsharp core.
