### ISSUE TITLE
Cannot use async in eff computation expression

### ISSUE THREAD

**Issue by viktorvan** [JohSand/Orsak#8]
The following section in the README.md leads me to believe that the `eff` Computation Expression should be able to handle `async`:

>This implementation makes use of resumable code to implement the computation expression builder for the lowest possible overhead. The builder also has various overloads for Bind, allowing for **friction free interop** with TaskLike<'a>, **Async<'a>**, Result<'T,'E> and more. It supports for, while, use, try-with and try-finally, and also applicative bind when the error-type supports +. While the computation expression is the intended way of working with effects, the corresponding module should contain all the expected functions.

But it seems it cannot? Am I doing something wrong?

```fsharp
[<Fact>]
let ``Can bind async in eff CE`` () =
    eff {
        let! myValue = async { return 1 } // <-- this line will not compile
        return myValue
    }
    |> Effect.runOrFail myTestRunner

```

**Comment by JohSand** [comment]
Hi.

It seems those overloads got lost somewhere, adding them right away.
